spring:
  #  sql:
  #    init:
  #      mode: always
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:post/,file:profile/,classpath:/static


jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdidsfdsfdfsdfsdfsdfsdfsd
  redis:
    host: localhost
    port: 6379
